# Generated by Django 5.0.3 on 2024-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=20)),
                ('lead_actor', models.CharField(max_length=20)),
                ('lead_actress', models.CharField(max_length=20)),
                ('ticket_fare', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Online', 'ONLINE'), ('Cash', 'Cash On Delivery')], max_length=10)),
            ],
        ),
    ]
